### PR TITLE
updated com.afollestad:material-dialogs

### PR DESCRIPTION
**Pull request by rhodey**
version 0.6.4.7 of material-dialogs was removed from jcenter so update to the most recent version and update its dependencies as well.

Fixes 3049
// FREEBIE

### CODE REVIEW

**Comment by agrajaghh** [comment]
Looks like all versions working with appcompat v21 got removed from jCenter, the new version are depending on resources not found in v21.
So we have to update appcompat or fork material-dialogs I guess....

**Comment by agrajaghh** [comment]
btw there is [android.support.v7.app.AlertDialog](https://developer.android.com/reference/android/support/v7/app/AlertDialog.html) in v22, but it doesn't replace `ProgressDialog` afaik. I guess it would be possible to use it for the other Dialogs and use `material-dialogs` for `ProgressDialog`s...

**Comment by moxie0** [comment]
based on past experience, switching to appcompat v22 is no minor change

**Comment by agrajaghh** [comment]
If you want to fork it or include the aar, 0.7.2.5 is the last version running with appcompat v21...

**Comment by rhodey** [comment]
@mcginty do you recall what issue we had with switching to appcompat v22 before? I could run some tests if you have any ideas. I had to delete my locale caches of the old material dialogs to confirm this issue and now can't build without this :P so all my builds have been using v22 and so far without any noticeable problems on my N5.

**Comment by mcginty** [comment]
@rhodey it usually ends up being namespace changes that conflict with custom ROM classes and theme changes that lead to white-text-on-white-bg or black-text-on-black-bg issues.

**Comment by rhodey** [comment]
@mcginty :| bummer, well, the repo is currently non-buildable. how do we wanna proceed?

**Comment by mcginty** [comment]
gotta start testing :)

**Comment by rhodey** [comment]
@mcginty took some of this and put it into a more complete pull with bug fixes for some dynamic theme related problems caused by the update of appcompat. closing.

**Pull request closed without merging**
