### PR TITLE
add dark theme to PassphrasePromptActivity

### PR DESCRIPTION
**Pull request by agrajaghh**
dark

### CODE REVIEW

**Comment by nwdev** [comment]
+1 Would really like to see this issue solved.. It drives me absolutely crazy.

**Comment by manhole11** [comment]
It drives me crazy too, the light theme kills my eyes

**Comment by agrajaghh** [comment]
rebased

**Comment by nwdev** [comment]
@meryl1 That's exactly why I can't stand it. Feels like my eyes are being burned.  Not sure why it hasn't been merged into an update..

**Comment by volcano99** [comment]
If I may dare, I would change the top bar and the password field to a different shade of gray. It would look more consistent with the general look/feel

**Comment by agrajaghh** [comment]
I tried making the action bar in a dark gray but it looked weird...

I'll have a look again

**Comment by agrajaghh** [comment]
Screenshot with the actionbar color and background from the other activites:
screenshot_2015-04-04-19-30-18

I still prefer the 100% black one, I guess its up to @mcginty to decide

**Comment by nwdev** [comment]
@agrajaghh I agree, all black looks much better.

**Comment by agrajaghh** [comment]
The white keyhole looks a bit weird in the dark theme, what do you think about a transparent one? (quick photoshop)

black_hole

**Comment by nwdev** [comment]
@agrajaghh Nice! I really like that one.

**Comment by mcginty** [comment]
If we want a "dark" version of the icon, we may as well use the dark blue color that we use for the FAB right now, too. Something like this maybe?

darklockscreenie

**Comment by agrajaghh** [comment]
@mcginty yeah, looks good. You wanted to do a icon rework, no? What were you planing to change except making it a circle? Otherwise I could do it...

**Comment by jeremymasters** [comment]
looks awesome!

**Comment by nwdev** [comment]
Can somebody explain what exactly is preventing this from being merged into an update? This is getting really old.....

**Comment by moxie0** [comment]
@nwdev We've been waiting for you to comment!

**Comment by nwdev** [comment]
@moxie0 Perfect!! So you'll roll it into the next update?

**Comment by McLoo** [comment]
sry for spamming, but @nwdev just made my day :grin:

**Comment by agrajaghh** [comment]
reminds me of https://twitter.com/searls/status/565931153564377089/photo/1 :satisfied:

**Comment by nwdev** [comment]
I wasn't trying to be an ass, I was serious.. I don't mind pitching in but it looks like the work has already been done.. Just was wondering why it hadn't been merged.. Does something ELSE need to be done to get it finalized??  @McLoo Glad I can keep somebody here entertained.. LOL

**Comment by agrajaghh** [comment]
@mcginty updated, the keyhole is now transparent and the dark icon is now a bit darker:

I also made the icon perfectly round and attached the psd file for pixelapse in a second commit

dark

**Comment by enkimatt** [comment]
@agrajaghh Seems like a lot of work for it to never be merged... @moxie0 said he was waiting for me to comment and still no updates... :-1:   lol

**Comment by enkimatt** [comment]
@agrajaghh If only all your hard work wasn't going to waste.....

**Comment by enkimatt** [comment]
You guys are a joke. Too coward to respond..instead just edit my post.   It's funny really, people tell you about issues with the software, somebody fixes all the code you jacked up to begin with and you can't even merge it into an update..

**Comment by moxie0** [comment]
If we're a joke, please leave us alone. We're working as fast as we can, and if @mcginty likes this, he'll merge it when he has time.  We're all huge fans of @agrajaghh and appreciate everything he does.  If you think we're idiots, feel free to write your own private messenger. You can even use our source (not that you'd want to, since it's so jacked up).

**Comment by enkimatt** [comment]
Never said anything bad about @agrajaghh looks like he does good work.. just sad seeing it go to waste. If you're so backlogged with stuff that you can't run a project why not bring on more help? Or will that hurt your ego, being the big bag Moxie Marlinspike, king of security....

**Comment by enkimatt** [comment]
Feel free to remove all of my threads and comments..  :)

**Comment by agrajaghh** [comment]
WTF, now @nwdev deleted his account... Hope he's working on his attitude.

**Comment by agrajaghh** [comment]
@mcginty btw you can delete [this one](https://www.pixelapse.com/openwhispersystems/projects/signal-android/views/assets/icon_monochrome.ai), its not used anymore (it was used for the push preference)

**Comment by enkimatt** [comment]
I have no attitude to work on. Moxie is a joke. Whoever edited my post
is a coward. Have fun fixing stuff that will never get merged....

**Comment by agrajaghh** [comment]
@moxie you should ban this guy from the repos and rename/close his issues #1504 #1512 #1539 #2296 #2328 #2756

What a childish beahviour...

**Comment by enkimatt** [comment]
Don't bother. I'm done.  Bye.,..

**Comment by agrajaghh** [comment]
So long, and thanks for all the fish... :wave:

**Comment by enkimatt** [comment]
No problem, asshole.

**Comment by volcano99** [comment]
On an off-topic note that isn't meant to bring this meaningless complaints any further:
His frustration means something. His anger brings up something that has long been a problem at whispersystems: interaction with users. It is unclear how the PRs get merged/worked on, the direction the app itself is taking is shady, the support forum isn't working, and everything is coming "real soon now". A lot of people are feeling frustrated. You can take a look at the support forum or twitter to see it.
You will have more and more people behaving like that or simply abandoning your products if you don't help the users understand how you work and what your plans in the future are.
This is of course just my opinion, arisen from several conversations with people who use/have used your apps. You can either ditch this user and think he's just an idiot or take a look at the actual problem behind his rude behavior.
That being said, peace and love to everybody.
End of off-topic.

**Comment by moxie0** [comment]
If people like that feel like they don't want to be involved, then we're doing something right.

**Pull request closed without merging**
