### PR TITLE
add icons to the preference categories

### PR DESCRIPTION
**Pull request by agrajaghh**
as discussed in the mailing list, here is my PR to add icons to the preference categories

light
dark

I got the icons I didn't design from here: https://github.com/google/material-design-icons
So I guess we shouldn't have copyright problems...

I kept the original names, or should I rename for example `ic_brightness_6_black.png` to `ic_appearance.png`? And should I include the original svg files as well?

### CODE REVIEW

**Comment by moxie0** [comment]
Is it intentional that the icons don't display on Gingerbread?

**Comment by agrajaghh** [comment]
@moxie0 no, I'll look into that...

**Comment by agrajaghh** [comment]
looks like support for icons was added with API Level 11. But shouldn't be a problem, no?

**Comment by manhole11** [comment]
+∞^∞
This looks great, I hope it will be merged soon. Makes it way easier to navigate through the settings.
Thank you!

**Comment by agrajaghh** [comment]
I replaced the push icon with the new TS icon. I also split up the artwork files into a seperate commit. I think you're managing them at pixelapse now, right?

I used the svg->png generator from #2304 (a bit modified). If I should include it and the svg's just tell me :blush: 

current state:
pref

**Comment by mcginty** [comment]
That looks wonderful @agrajaghh! Only comment at the moment is that the icons look like #ff000000 black, which is now against material design recs (which we certainly don't follow perfectly throughout the app).

It looks like their guidelines recommend 87% alpha on black, which might make them look a bit less intrusive as they are currently darker than the text.

**Comment by agrajaghh** [comment]
@mcginty oh right, I changed it to black with 87% opacity, but I left the gray ones at #D0D0D0 with 100% opacity, is that okay?

Btw, It seems like you increased the spacing/padding between the categories with one of your recent changes, so the options don't fit on my whole screen anymore ;) Was this on purpose?

**Comment by mcginty** [comment]
I'm innocent! :) That's likely AppCompat v21 changing some defaults - I didn't explicitly change preference paddings.

**Comment by McLoo** [comment]
@agrajaghh somehow I miss the horizontal divider lines in the select theme / language / led color / led blinky dialogs. Maybe others too. Didn't search further...

**Comment by jeremymasters** [comment]
In the dark theme right now, when the push checkbox is checked, the background of the checkbox turns a yucky sea green color.  I noticed in these previews that's not the case.  I like this render over the pukey sea green along with the icons!

**Comment by agrajaghh** [comment]
@McLoo can you please post a screenshot? I don't know what you mean.

**Comment by agrajaghh** [comment]
@jeremymasters are you talking about all the checkboxes in the dark theme?

**Comment by jeremymasters** [comment]
@agrajaghh yes, about the checkboxes.  Sorry about any derailing of thread!  I need to get out of the way of progress sometimes! :)

**Comment by agrajaghh** [comment]
@jeremymasters just open another issue and make some suggestions for better colors. lets see what the devs will say...

**Comment by McLoo** [comment]
Aah, my bad! Seems that is a CM12 issue.  Sorry for disturbing. 
screenshot_2015-02-11-10-01-39

**Comment by agrajaghh** [comment]
@McLoo just to clarify, the screenshot you posted is on CM12? It's looking exactly the same on my stock Nexus 4 with 5.0. Are you expecting a line between "Light" and "Dark"?

**Comment by McLoo** [comment]
@agrajaghh correct. CM12. expecting a line between the radio buttons.
On my KK there are seperator lines - so maybe just another 'tweak' from google...

**Comment by agrajaghh** [comment]
Yep, I guess that's the material design. It looks okay to me...

**Comment by mcginty** [comment]
@agrajaghh I took your artwork commit and threw it into Pixelapse. Also decreased the side padding on the preferences fragment since it seemed a little excessive :).

**Comment by agrajaghh** [comment]
@mcginty cool, looking better with smaller padding, unfortunately still not fitting on my screen ;)

**Pull request closed without merging**
