### PR TITLE
enable LeakCanary in debug builds

### PR DESCRIPTION
**Pull request by mcginty**

### CODE REVIEW

**Comment by herbig** [comment]
This is great.  LeakCanary has been pretty amazing in my experience with it thus far.

**Comment by moxie0** [comment]
I'd like to keep the debug and release builds as identical as possible.  Maybe this should be in a different build target?

**Comment by rhodey** [comment]
Can one of the admins verify this patch?

**Comment by mcginty** [comment]
good idea, will update when i have a free moment

**Comment by rhodey** [comment]
how's about the `debugTest` build target?

**Pull request closed without merging**
