### PR TITLE
Fix "Signal and Signal" string

### LINKED ISSUE #4162: String refers to "Signal and Signal" users
In 4044da8 , the string,

    Free private messaging to TextSecure and Signal users

was changed to

    Free private messaging to Signal and Signal users
    
"Signal and Signal" does have a nice ring to it, for a PI or law firm. :heart:

### PR DESCRIPTION
**Pull request by unrulygnu**
Fixes #4162
// FREEBIE

### CODE REVIEW

**Comment by McLoo** [comment]
nice, but: #4157

**Comment by unrulygnu** [comment]
Me slow.

**Comment by McLoo** [comment]
Naaa. He's fast :dash:  :wink:

**Comment by unrulygnu** [comment]
:laughing: :+1:

**Pull request closed without merging**
