### PR TITLE
new image for ic_missing_thumbnail_picture

### PR DESCRIPTION
**Pull request by agrajaghh**
I replaced the oldschool `ic_missing_thumbnail_picture` drawables. Its now a combination of `ic_photo` and `ic_report_problem`. I used the red color from `error_round.xml` since I couldn't make a nice black and white icon.

The illustrator file is in a seperate commit if you want to upload it to pixelapse instead...

Its looking like this now:
ic_missing_thumbnail_picture

before:
ic_missing_thumbnail_picture_old

### CODE REVIEW

**Comment by mcginty** [comment]
how's it look on dark theme?

**Comment by agrajaghh** [comment]
sry, forgot the screenshot: 
screenshot_2015-04-14-21-44-45

I could invert ic_photo, but I think it's okay like that, no?

**Comment by mcginty** [comment]
if we keep with a light-ish gray, i think we'd win on contrast between both themes. what are your thoughts?

warning: poorly photoshopped screenshot
untitled-1

**Comment by agrajaghh** [comment]
much better, the contrast on the light theme was really high anyway...

**Comment by agrajaghh** [comment]
updated:
screenshot_2015-04-14-22-16-28
screenshot_2015-04-14-22-15-41

**Comment by mcginty** [comment]
nice, i like it!

**Comment by mcginty** [comment]
Think you forgot to update the Illustrator file with the new color.

**Comment by agrajaghh** [comment]
damn you're right, updated the illustrator file 

Its funny how the gray looks much darker with the light theme... The human vision is so weird ;)

**Comment by moxie0** [comment]
2.12.0 hasn't been merged yet, this should have gone in there

**Comment by agrajaghh** [comment]
@moxie0 I restored the branch, if thats what you meant...

**Comment by moxie0** [comment]
@agrajaghh correct

**Pull request closed without merging**
