### PR TITLE
remove unused resources

### PR DESCRIPTION
**Pull request by agrajaghh**
I saw these two png files in the density-independent res/drawables folder and it seems like they are never displayed. `ImageButton` and `ImageView` both contain `android:visibility="gone"` and are never accessed

### CODE REVIEW

**Comment by mcginty** [comment]
good thing they're never displayed if they're density-independent!

**Comment by agrajaghh** [comment]
hehe. What do you mean by "they're safe"?

**Comment by mcginty** [comment]
safe to remove, that is.

**Comment by agrajaghh** [comment]
Ah ok, I see ...

**Pull request closed without merging**
