### PR TITLE
Acquire wakelocks for incoming messages.

### PR DESCRIPTION
**Pull request by moxie0**
Please also see the accompanying change:
https://github.com/WhisperSystems/jobmanager/commit/c7a1ac531018646557bb11d0830c9c7a136a7999

### CODE REVIEW

**Comment by mcginty** [comment]
the `withWakeLock(boolean)` still reads strange to me but code lgtm!

**Comment by agrajaghh** [comment]
Couldn't it be problematic to set a wakelock without a timeout? For example in `PushReceiveJob`: What would happen when the job gets added (and so the wakelock gets acquired) but the requirement isn't present (no internet connection). Wouln't the phone be awake until the internet connection is back or did I miss something?

**Comment by moxie0** [comment]
@agrajaghh They're only set without a timeout if there are no requirements.

**Comment by agrajaghh** [comment]
@moxie0 shame on me, you're right....

**Pull request closed without merging**
