### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by rouzbeh84**
Including iOS link in the README and link to app in App Store

### CODE REVIEW

**Comment by steko** [comment]
The iOS app is in a separate repository https://github.com/WhisperSystems/Signal-iOS

**Comment by mcginty** [comment]
Yeah the readme isn't meant to be an advertisement for all our products, just the contents of this repo. Thanks!

**Comment by rouzbeh84** [comment]
Gotcha! Thanks for the responses. Use it on android and thought it was such a great idea was just trying to spread the word out as much as possible.

**Comment by mcginty** [comment]
No problem! A more fitting README link, once we are rebranded to Signal, might be to say something like "For the iOS Signal source, go to XXX" but we're not fully renamed just yet since it's still in beta.

Thanks again for contributing.

**Pull request closed without merging**
