### PR TITLE
fixed DynamicLanguage to handle sporadic Locale changes

### LINKED ISSUE #2815: Dynamic language issue after rotating screen
As no one wants this linked to his issue, here's a new one:

As  mentioned in https://github.com/WhisperSystems/TextSecure/issues/2684#issuecomment-86957063 I noticed that too.
Steps to reproduce:
- system locale german, TS language english
- have conversation list open
- enjoy english time span descriptions (mins, hours)
- ~~leave phone alone for a while (a view minutes with turned of screen)~~
- edit: rotate the screen (e.g. watch a video on YouTube on full screen)
- watch your conversation list turning `mins` to `Minuten` and `hours` to `Stunden`
- 3dot menu language is german too then
  
  no relevant log entry
  Sony Z1 compact 4.4.4 stock
  TS 2.9.0

### PR DESCRIPTION
**Pull request by rhodey**
The Locale on Context.getResources().getConfiguration() was sporadically
changing due to android:configChanges such as orientation and also sometimes
onActivityResult(), so...

1) added onConfigurationChanged and onActivityResult methods to DynamicLanguage
2) switched all activites to inherit from BaseActivity or BaseActionBarActivity
3) moved all uses of DynamicLanguage into base activity classes
4) added missing super.onActivityResult call to KeyScanningActivity
5) removed unused imports along the way

Fixes #2815, #2898
// FREEBIE

### CODE REVIEW

**Comment by McLoo** [comment]
Why not onPreCreate incBaseActivity or BaseActionBarActivity?

**Comment by rhodey** [comment]
no worries :) I definitely appreciate the help with review. eventually we should be able to move dynamic theme in this same way but I'm told we need to style a few remaining views first.

**Comment by McLoo** [comment]
Ah, you mean registration process, passphrase change and lock screen 😊

Will surely go on reviewing. Much to learn from you guys there.

**Comment by rhodey** [comment]
forgive my build bot for messing with the status of this PR :(

**Pull request closed without merging**
