### PR TITLE
update APN list, fix MMSC issues

### PR DESCRIPTION
**Pull request by mcginty**
Updated our APN xml files from Hangouts and CM. Also modified apntool to attempt to normalize typos in IP addresses. I think somebody hand-typed or like... OCR'd these APNs.
* 02.co.uk corrected to o2.co.uk
* IPs with leading zeros in their octets have their zeros removed
* IPs with five octets 1.2.3.4.5 are rewritten as 1.2.3.4:5 since I'm assuming they meant for it to be a port.

You can see from the python output how many MMSCs and proxies are invalid in Google's and CM's files...
```
Opening apnlists/all.xml
normalize MMSC: http://mmsc.mms.02.co.uk:8002 => http://mmsc.mms.o2.co.uk:8002
normalize MMSC: http://mmsc.mms.02.co.uk:8002 => http://mmsc.mms.o2.co.uk:8002
normalize MMSC: http://172.24.97.152.10021/mmsc => http://172.24.97.152:10021/mmsc
normalize MMSC: http://10.152.10.70.38090 => http://10.152.10.70:38090
normalize MMSC: http://10.152.10.70.38090 => http://10.152.10.70:38090
normalize proxy: 010.010.010.011 => 10.10.10.11
normalize proxy: 010.010.010.011 => 10.10.10.11
normalize proxy: 010.143.156.005 => 10.143.156.5
normalize proxy: 010.012.003.011 => 10.12.3.11
normalize proxy: 195.222.056.041 => 195.222.56.41
normalize proxy: 172.017.085.131 => 172.17.85.131
normalize proxy: 212.245.244.011 => 212.245.244.11
normalize proxy: 010.000.000.010 => 10.0.0.10
normalize proxy: 010.000.000.010 => 10.0.0.10
normalize proxy: 194.048.124.071 => 194.48.124.71
normalize proxy: 010.012.000.020 => 10.12.0.20
normalize proxy: 010.012.000.020 => 10.12.0.20
normalize proxy: 213.094.078.133 => 213.94.78.133
normalize proxy: 213.094.078.133 => 213.94.78.133
normalize MMSC: http://mmsc.mms.02.co.uk:8002 => http://mmsc.mms.o2.co.uk:8002
normalize proxy: 212.183.137.012 => 212.183.137.12
normalize proxy: 212.183.137.012 => 212.183.137.12
normalize proxy: 212.183.137.012 => 212.183.137.12
normalize proxy: 130.244.202.030 => 130.244.202.30
normalize proxy: 193.012.040.014 => 193.12.40.14
normalize proxy: 193.012.040.038 => 193.12.40.38
normalize proxy: 010.010.030.060 => 10.10.30.60
normalize proxy: 192.168.094.023 => 192.168.94.23
normalize proxy: 192.168.094.023 => 192.168.94.23
normalize proxy: 192.168.010.010 => 192.168.10.10
normalize proxy: 192.168.010.010 => 192.168.10.10
normalize proxy: 213.158.194.057 => 213.158.194.57
normalize proxy: 192.168.006.138 => 192.168.6.138
normalize proxy: 192.168.006.135 => 192.168.6.135
normalize proxy: 212.088.139.44 => 212.88.139.44
normalize proxy: 010.085.085.085 => 10.85.85.85
normalize proxy: 212.031.096.161 => 212.31.96.161
normalize proxy: 010.011.240.007 => 10.11.240.7
normalize proxy: 091.185.221.085 => 91.185.221.85
normalize proxy: 192.168.246.005 => 192.168.246.5
normalize proxy: 172.016.007.012 => 172.16.7.12
normalize proxy: 172.016.007.012 => 172.16.7.12
normalize proxy: 213.172.091.046 => 213.172.91.46
normalize proxy: 195.047.255.007 => 195.47.255.7
normalize proxy: 100.001.201.172 => 100.1.201.172
normalize MMSC: http://176.000.000.021 => http://176.0.0.21
normalize proxy: 194.126.053.064 => 194.126.53.64
normalize proxy: 192.168.023.007 => 192.168.23.7
normalize proxy: 202.139.083.152 => 202.139.83.152
normalize proxy: 172.030.038.003 => 172.30.38.3
normalize proxy: 010.202.002.040 => 10.202.2.40
normalize proxy: 163.121.178.002 => 163.121.178.2
normalize MMSC: http://172.025.049.009/servlets/mms => http://172.25.49.9/servlets/mms
normalize MMSC: http://172.024.97.152:10021/mmsc => http://172.24.97.152:10021/mmsc
normalize proxy: 172.024.97.158 => 172.24.97.158
normalize proxy: 010.008.008.009 => 10.8.8.9
normalize proxy: 010.100.082.004 => 10.100.82.4
normalize MMSC: http://10.152.10.70.38090 => http://10.152.10.70:38090
normalize proxy: 192.168.010.200 => 192.168.10.200
normalize proxy: 196.031.116.250 => 196.31.116.250
normalize proxy: 200.068.032.239 => 200.68.32.239
normalize proxy: 172.025.007.031 => 172.25.7.31
normalize proxy: 170.051.255.240 => 170.51.255.240
normalize proxy: 170.051.255.240 => 170.51.255.240
normalize proxy: 172.025.007.031 => 172.25.7.31
normalize MMSC: http://200.222.042.204:8002 => http://200.222.42.204:8002
normalize proxy: 172.017.008.011 => 172.17.8.11
normalize proxy: 200.058.228.081 => 200.58.228.81
normalize proxy: 213.026.205.001 => 213.26.205.1
normalize proxy: 010.000.002.029 => 10.0.2.29
normalize proxy: 170.051.255.240 => 170.51.255.240
Processed: 4075 apns (Elapsed Time: 0:00:00)
Successfully written to apns.db
Successfully gzipped to apns.db.gz
```

### CODE REVIEW

**Comment by agrajaghh** [comment]
WTF, OCR? They probably received this list by fax... 
Were the errors in googles list or CMs?

**Comment by mcginty** [comment]
looks like the leading zeros are a CM issue, the "02" and 5-octet IPs are Google.

**Comment by mcginty** [comment]
(I combine the lists when creating the db)

**Comment by moxie0** [comment]
lgtm

**Pull request closed without merging**
