### PR TITLE
use switchcompat instead of checkboxes for some preferences

### PR DESCRIPTION
**Pull request by agrajaghh**
Appcompat v22 fixed a display bug of SwitchCompat on tvdpi devices, so its useable now. There is still a minor alignment issue on tvdpi which will be solved in the next release, see comment 33 at https://code.google.com/p/android/issues/detail?id=78262#c33 . So perhaps it makes sense to wait for the next appcompat release...

screenshot_2015-03-13-19-03-36
screenshot_2015-03-13-19-03-46
screenshot_2015-03-13-19-03-58

### CODE REVIEW

**Comment by mcginty** [comment]
Let's hold back on upgrading AppCompat, I'd like to test it for regressions before changing it in master. I am forever skeptical of that library "just working" any more.

**Comment by agrajaghh** [comment]
haha, I thought so :smile:

I'll reopen this when we're on v22 ...

**Comment by mcginty** [comment]
I thought SwitchCompat was available in v21?

**Comment by agrajaghh** [comment]
@mcginty yes but not usable on some devices. Thats why I waited for the fix...
On tvdpi the "circle" is just missing... see https://code.google.com/p/android/issues/detail?id=78262

**Comment by mcginty** [comment]
hahahaha

awesome.

**Comment by agrajaghh** [comment]
You're loving appcompat now even more, right?  :stuck_out_tongue:

**Pull request closed without merging**
