### PR TITLE
fix message details scrolling

### LINKED ISSUE #2686: Message Details v2.7.0b1
There's no scrolling in Message Details. A long SMS does fill the screen, isn't fully displayed, and the details aren't shown.

Regards
C
screenshot_2015-03-14-14-17-01

### PR DESCRIPTION
**Pull request by rhodey**
moved message container from message_details_activity into message_details_header to fix scroll on overflow.

Fixes #2686
// FREEBIE

### CODE REVIEW

**Comment by rhodey** [comment]
@mcginty tested on GB

**Comment by mcginty** [comment]
left-right padding squishes it in - we should fix that so it looks just like the message in the conversation

**Comment by rhodey** [comment]
@mcginty done, good catch. the diff on `message_details_header.xml` looks weird now but is simply an additional `LinearLayout` to keep the 10dp padding for the message header but exclude it for the message bubble `FrameLayout` as before.

**Comment by rhodey** [comment]
rebased with master and took some screen shots to verify that everything except the scroll behavior appears as before http://imgur.com/a/bjwaE#0

**Comment by rhodey** [comment]
rebased with master and corrected commit messages to better fit our style.

**Comment by mcginty** [comment]
merged into https://github.com/WhisperSystems/TextSecure/tree/2.13.0

**Pull request closed without merging**
