### PR TITLE
limit displayed message length to 1024 characters.

### PR DESCRIPTION
**Pull request by phryneas**
* limit displayed message length to 1024 characters.
* added a "messageTooLongIndicator" that can be clicked to display the
full content of a truncated message

this should concern issues #2252 #2226 and  #2271 (and possibly more)

even though it does not resolve the problem of corruped messages, corrupted messages won't crash textsecure any more and it is possible to delete them

this also removes a possible DOS on a user's history with another user by sending a very long message that will crash on display and thus prevent scrolling back in history

logcat for the case of a too big message crashing TS:

    01-04 14:18:57.523  14631-14642/org.thoughtcrime.securesms I/art﹕ [ 01-04 14:18:58.045 14631:14642 I/art      ]
        Wrote stack traces to '/data/anr/traces.txt'
    01-04 14:19:00.477  14631-14631/org.thoughtcrime.securesms A/libc﹕ new[] failed to allocate 296136 bytes
    01-04 14:19:00.477  14631-14631/org.thoughtcrime.securesms A/libc﹕ Fatal signal 6 (SIGABRT), code -6 in tid 14631 (crime.securesms)

(content of /data/anr/traces.txt did not seem too interesting to me but if requested, I can provide it)

### CODE REVIEW

**Comment by agrajaghh** [comment]
You have to remove the comments to follow the code guidlines

**Comment by phryneas** [comment]
Oh sorry I didn't know there even were such a thing as code guidelines.
I found them now in the wiki and will clean the code up accordingly.

To prevent that in the future: Could a link the code guidelines maybe be added to the README.md under "Contributing Code" or at least the BUILDING.md?

**Comment by phryneas** [comment]
Okay, cleaned up and spacing should be two-spaces now, too.

**Comment by mcginty** [comment]
So, in push messages we limit the length to 1000. If we get a message over that, I think we should just either error out or cut it off, not allowing them to expand the text. I think that's better than having a button that questionably crashes the app :P

**Comment by phryneas** [comment]
I wasn't aware of that - removing that part of the code would be okay with me.

But as the code is already written just as a suggestion: 

Even 1K messages take a while to render on my S4, which is not really a low-spec phone.
So it could be considered to decrease the DISPLAY_MAXLENGTH to something like 500 (or even lower?) to increase overall rendering speed and scrolling smootheness and just remove the warning part from the button text as as you are right, 1K messages will probably crash nobody.

(As a comparison: I have some ~16K messages. Those take quite a long time to render, but still no crashes at that point)

**Comment by phryneas** [comment]
I reduced it to "just show 1000 characters" as suggested by @mcginty .

While I think the other functionality might be useful, I agree that it might take some discussion and I feel it's more important to push this simple fix to the codebase as soon as possible, as it resolves a number of issues. (or at least makes TextSecure still usable for those experiencing these issues)

**Pull request closed without merging**
