### PR TITLE
Add camera preview to message composition

### PR DESCRIPTION
**Pull request by turtlekiosk**
Long overdue work from WBoC15, this adds a Facebook Messenger/Google Messenger style camera preview that lets you quickly take photos without exiting the ConversationActivity view. (part of #520) ~~This does not currently encrypt the files because I didn't want the work to conflict with the changes from the Glide PR.~~ (EDIT: Since the Glide PR got merged in, I updated the branch.) Also, this probably fixes and definitely affects #2930 because the new view cannot handle not being redrawn on rotation. (QuickCamera.java requires knowledge of the device orientation to rotate the camera preview display and image properly).

screenshot_2015-04-20-12-46-32 portrait
landscape

### CODE REVIEW

**Comment by turtlekiosk** [comment]
Note: I made the decision to not support half-expanded camera preview/fling on Android versions < 4.0 and only show a full screen preview. I looked at other apps with a similar UI element, Google Messenger, Textra, and Facebook Messenger, and saw that the first two did not support < 4.0 and that Facebook Messenger had made the same decision regarding full screen camera previews on those devices. Let me know if this is an important issue.

**Comment by mcginty** [comment]
The experience is pretty choppy on my Gingerbread phone. I'm wondering if we should only offer this live preview to Android > 4.0 at least for the first release of it.

**Comment by turtlekiosk** [comment]
That'd be fine with me if you think that's the best way to go

**Comment by bungabunga** [comment]
hey, @turtlekiosk, thank you for implementing a long awaited TextSecure feature!

your implementaton looks very nice but what i see here, is a usability problem. i think you can't make decent photos without a full screen preview. i know Google Messenger, Textra and Facebook Messenger are doing the same, but they don't really give a fuck about taking decent photos. they're looking at it strictly from a "gadget perspective" not from usability stand point. if you want to make a decent photo of someone (or something) you really got to have the bigest preview screen possible.

so i'm asking you if it's possible to have at least an option to switch to a full screen preview in your implementation?

thanks!

**Comment by McLoo** [comment]
@bungabunga if I got it right, you can tap the lower right icon to expand the photo view

**Comment by bungabunga** [comment]
@McLoo: that's great! in this case it would be cool to change the icon to be more explanatory. the icon currently in use can have different meanings if used in a context of a camera viewfinder. 
fullscreen-icon-logo-black
full screen1
fullscreen_alt-512

**Comment by turtlekiosk** [comment]
the icon I use is p standard:

Google Messenger:&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Textra:
screenshot_2015-04-30-10-00-04 screenshot_2015-04-30-10-03-26

Also, I updated the original comment to include a gif of the view in action.

**Comment by bungabunga** [comment]
sorry, then my comments are pointless...

**Comment by agrajaghh** [comment]
@turtlekiosk nice work! Really like the UX :blush: 

But unfortunately it's still buggy, while extensive testing my phone crashed and restarted several time times (Nexus 4, Stock 5.1). Unfortunately logcat is empty after restarting... I'll try to reproduce this.

Besides that, the aspect ratios don't match the native camera one's:
Portrait small: ~1,44 ( I guess thats okay since the image is cropped anyway)
Portrait fullscreen: 0,56 (1,78)
Landscape fullscreen: 1,77

The native camera is taking pictures with 1,33 or 0,75

Would it also be possible to keep the camera view open while rotating?

**Comment by turtlekiosk** [comment]
Thanks for checking the view on your device, I'll def follow up on that. Regarding keeping the camera view open, yeah, if we agree that's the ux we want, I can make it happen.

**Comment by turtlekiosk** [comment]
Also I want to clarify that the images are taken from the preview frame, not from converting the raw image sensor data. The reasons for this are:

1. It's much faster to grab a frame and makes the interface much snapper.
2. It takes much less memory, particularly handy when rotating the picture. (Some camera apps don't rotate images, they just store exif data detailing the proper orientation.) Rotating a full resolution image can easily cause an OOM exception.

The cons are:
1. Lower resolution images.
2. Images sizes are dependent on the preview sizes returned by the Camera API rather than native image format size.

But if anyone has any answers to resolve these issues, please lmk!

**Comment by mcginty** [comment]
@turtlekiosk did you look into just using the camera logic from https://github.com/commonsguy/cwac-camera? Seems like from their repo that there are many device-specific strangenesses that we might be able to avoid by using their code.

**Comment by turtlekiosk** [comment]
I hadn't considered it, but sounds like a good idea, I don't think it'd be too much work to plug that in either.

**Comment by rhodey** [comment]
Can one of the admins verify this patch?

**Comment by mcginty** [comment]
Going to close this in favor of the CWAC rework.

**Pull request closed without merging**
