### PR TITLE
adapt SMS strings in preferences

### PR DESCRIPTION
**Pull request by agrajaghh**
Fix for #2672 

* changed "Push messages" to "TextSecure messages"
* changed sms summary to: "On", "Off", "SMS on, MMS off", "SMS off, MMS on"
* changed SMS pref on >= KITKAT to: "SMS Disabled" and "SMS Enabled"
* removed unused strings

Please comment if you have better suggestions for the strings :blush: 

**Android 2.3 settings:**
2 3_settings

**Android 2.3 SMS and MMS:**
2 3_sms

**Android >= KITKAT settings:**
5 0_settings

**Android >= KITKAT SMS and MMS (disabled):**
5 0_sms_disabled

**Android >= KITKAT SMS and MMS (enabled):**
5 0_sms_enabled

**Advanced:**
5 0_advanced

### CODE REVIEW

**Comment by Geblaat** [comment]
Imho it would be good to mention encryption or security, because since encrypted SMS is gone, you now need to register for TextSecure messages if you want encryption. How about "Use encrypted messaging and avoid SMS fees by using the data channel for secure communication with other TextSecure users"?

**Comment by agrajaghh** [comment]
what about just adding "encrypted"?
> Increase privacy and avoid SMS fees by using the data channel for encrypted communication with other TextSecure users

**Comment by Geblaat** [comment]
Yes, that would work as well I guess.

**Comment by jtracey** [comment]
IMO, if push settings are neccessary to keep, they should be burried in Advanced Settings. It made sense to put it where it is when it was an experimental way of doing things, but now, I can't immagine very many circumstances where someone would actually even need to do this. Putting an option to disable the entire point of the app as the first thing you see in settings just seems somewhat dangerous to me.

**Comment by agrajaghh** [comment]
@jtracey good point since there is the non-dismissable banner to register for push messages anyway. I'll move it into the advanced options ...

**Comment by agrajaghh** [comment]
moved the "TextSecure messages" option to advanced and updated the screnshots

**Comment by moxie0** [comment]
@mcginty You cool with these changes?

**Comment by mcginty** [comment]
@moxie0 @agrajaghh looks good. I think the subtext under "TextSecure messages" is too long. Maybe something more to the point like "Free private messaging to TextSecure and Signal users." The registration page will have more opportunity for details.

**Comment by mcginty** [comment]
On that note we can probably remove "viewing and storing" from the incoming SMS and MMS descriptions.

**Comment by agrajaghh** [comment]
@mcginty changed and updated the screenshots

**Pull request closed without merging**
