### PR TITLE
Memory leak fix for ContactSelectionListAdapter

### PR DESCRIPTION
**Pull request by herbig**
FREEBIE Relates to #3094 #3092 #3084

Because ContactSelectionListItem is used as a RecipientModifiedListener, it leaks its context (NewConversationActivity/PushContactSelectionActivity), which can lead to OOM crashes.

Here we keep a reference to the inflated views in order to unbind them whenever they become unused.  Because views are recycled while scrolling the adapter, the HashSet stays the same size dependant on how many rows are visible on screen, regardless of how many contacts you've scrolled through.

I used Square's new LeakCanary library to detect the leak and confirm the fix.

### CODE REVIEW

**Comment by moxie0** [comment]
why not just remove the listener after the callback?

**Comment by herbig** [comment]
Yeah, that would be much easier.  I assumed the contact could be modified more than once, but is the listener really only for downloading the image?

**Comment by moxie0** [comment]
yeah, once a recipient object is resolved it's done.

**Comment by herbig** [comment]
I see.  So setContactPhotoImage calls setImageDrawable (which could be null at that time) then sets the listener, in case the image is in the process of downloading.  Let me fix the pull request..

**Comment by herbig** [comment]
Ok, that should be better.

**Comment by mcginty** [comment]
This is brand new code so I don't think it's a root cause for #3094 #3092 #3084, but thanks so much and good catch!

**Comment by herbig** [comment]
No problem.  I'd like to do a more thorough run through the app and patch up any leaks I find, if that works for you.  How do you guys normally work, I don't want to step on your toes if you're already looking into things.

**Comment by mcginty** [comment]
We'd love that! Finding bugs is the opposite of stepping on toes. I periodically check for memory leaks if I notice a suspiciously-high memory when testing, but leakcanary looks really promising for more continuous checking (akin to StrictMode).

**Comment by herbig** [comment]
Now that it's not 2am and I'm looking over this again, just that one line won't fix the issue.

Listeners are currently registered on every ContactSelectionListItem, whether they're downloading an image or not.  This means those that already have an image or don't have one at all never call onModified() and thus will never unlisten.

**Comment by mcginty** [comment]
@herbig created a new issue this morning detailing just that :)

**Comment by herbig** [comment]
Nice. My original commit from last night would fix the issue, but it may be overthinking it:

93809c3677746ab671b0a9d28a221545c77c9f05

**Comment by herbig** [comment]
@mcginty Scratch that.  There are a number of leaks associated with RecipientListeners, not just here, and not just within Adapters, so I agree with #3224 in that they should only hold a weak reference.

**Pull request closed without merging**
