### PR TITLE
prevent SMS/MMS composition in UI when messaging to non-TextSecure users

### PR DESCRIPTION
**Pull request by calvinhu4**
Re: Issue #2161, #2245

### CODE REVIEW

**Comment by rbu** [comment]
What is holding back the merge?

**Comment by moxie0** [comment]
@rbu We were waiting for you to write something!

**Comment by rbu** [comment]
@moxie0 I am honestly wondering if there is anything keeping this from being merged. If there is, possibly I could do something to help. I do not understand how sarcasm helps this discussion.

**Comment by mcginty** [comment]
Closing this, since we've changed how SMS is handled after the encrypted SMS change. Also, if we do something here we'd probably want to still allow for the auto-upgrade to a TextSecure message happen if we find out the user has recently registered.

**Pull request closed without merging**
