### PR TITLE
Changed bubble message font size to match the input text message.

### PR DESCRIPTION
**Pull request by killickjoe**
This should fix the issue #2769, where the input text message size was different to the actual message (sent and received). Tested on several different devices.

### CODE REVIEW

**Comment by mcginty** [comment]
that looks pretty massive to me

**Comment by mcginty** [comment]
I think we should just make the composition text smaller.

**Comment by agrajaghh** [comment]
actually, I don't mind it a bit bigger. Whatsapp has it one or two sizes bigger as the bubbles as well..

**Comment by mcginty** [comment]
WhatsApp has it a bit bigger, Messenger has it about the same size. I don't have strong opinions either way on composition font size, other than I don't want to make the clickzone of the composition any smaller.

**Comment by killickjoe** [comment]
If it'd help, we can set a default size, then use volume button listener to grow or shrink size as user desires.

**Comment by mcginty** [comment]
I don't think we should override controls in a way that violate users' assumptions. Personally, I like having the ability to control my music volume while still in a TextSecure conversation :). Going to close this issue for now since I don't think it's quite what we want.

Thanks!

**Pull request closed without merging**
