### PR TITLE
message timestamps update onResume()

### LINKED ISSUE #2519: Time stamps very slow to update
Hi all! I'm running text secure 2.5.3 on a Moto G (XT1033 falcon_asia_ds). Running android 5.0 (LXB22,46-28). I'm using the app primarily as a texting replacement as none of my contacts use Text Secure. [Debug log](https://gist.github.com/anonymous/faa0bc4a16b4d923ca56)

I've noticed that time stamps are extremely slow in updating. If I've sent a text, then navigated out of the app, then go back into the app after a number of minutes, chances are the time stamp shows "now" or "1 min" or whatever. The time stamp only updates after maybe 10-20 seconds. I've never noticed this problem on any other texting app.

### PR DESCRIPTION
**Pull request by rhodey**
modified conversation view and conversation list view to update message timestamps onResume. Fixes #2519

### CODE REVIEW

**Comment by moxie0** [comment]
in an onCreate() situation, isn't this going to result in loading the entire data set, then immediately refreshing it?

**Comment by rhodey** [comment]
@moxie0 good catch, in the `onCreate()` case the `ConversationAdapter.notifyDataSetChanged()` call would happen needlessly in `onResume()`.

Another option is to initialize the list adapter in `onResume()` but on it's own that also results in even more waste.

I think keeping track of `onPause()` and `onResume()` with a boolean `fragmentHasPaused` would be the most efficient and clean way about this. `onPause()` set `fragmentHasPaused = true`, `onResume()` if `fragmentHasPaused` then `ConversationAdapter.notifyDataSetChanged()`, `fragmentHasPaused = false`

**Comment by rhodey** [comment]
the basics of this seem to be that we need to initialize a list once and force refresh a list `onResume()` but not immediately after `onCreate()`-- I can't see another way of doing that without tracking `onPause()`.

**Comment by rhodey** [comment]
modified to include the `onPause()` tracking boolean rebased and pushed.

**Comment by agrajaghh** [comment]
isn't it enough to set `hasPaused = true;` at the end of `onResume()`? So `handleRefreshAdapter()` won't be called the first time, but the second time (and afterwards) and you don't have to override `onPause()`... Perhaps it would be more clear if you rename the variable to something like `isCreated`?

**Pull request closed without merging**
