### PR TITLE
Fix for inconsistent thumbnail aspect ratio

### LINKED ISSUE #2676: Image bubble size differs in detail, outgoing/incoming messages
Seems as if the max width is different - didn't code check... 
Conversation 
screenshot_2015-03-14-03-31-05 01 01

Detail 

screenshot_2015-03-14-03-29-52 01

### PR DESCRIPTION
**Pull request by mcginty**
Problems arose from any app that targets below API 19 and uses
views that rely on RelativeLayouts giving correct measurement specs to
their onMeasure().

Resolves #2676

### CODE REVIEW

**Comment by moxie0** [comment]
i live in ignorance, so lgtm, but that means very little

**Comment by moxie0** [comment]
But is there a reason this wrapper layout isn't just a part of the ForegroundImageView?

**Comment by mcginty** [comment]
@moxie0 I tried that at first, but ended up having other layout problems so I kept it simple instead. Can revisit later.

**Comment by moxie0** [comment]
When is this mythical "later?"  =)

**Comment by mcginty** [comment]
defining later is on the roadmap

**Pull request closed without merging**
