### PR TITLE
Prevent NPE when thumbnail click not set

### LINKED ISSUE #3042: NPE: ThumbnailView, tap preview icon when file not found
encountered this while running an unmodified debug build of 27a5b7dd5c588abd677b6947c896df410d67a0f2

sequence of events were:
1) send a bunch of text messages
2) send a bunch of media messages
3) do the same while screwing around with airplane mode
4) attach image
5) image preview is an error icon (may have been `ic_action_warning_red` or `ic_missing_thumbnail_picture`, can't remember)
6) click on error image preview
7) crash

I then tried to reproduce by simply returning to the convo and reattaching the same image, crash again. Did this a few more times and once the image preview was entirely blank (but still took up the space it should), clicked on that too, crash. While in this crashable state I attempted to reproduce this using a different attachment, no crash. Thinking it may have had something to do with cache I tried another different image that definitely should not have been in cache, also no crash.

Eventually through some multi-step process I can't recall I was able to stop the error image from showing up for that one attachment and thus stop the crashing.

debug log >> https://gist.github.com/anonymous/266cafd4ee10f5f3e380

crash
```
E/AndroidRuntime(14933): FATAL EXCEPTION: main
E/AndroidRuntime(14933): Process: org.thoughtcrime.securesms.sushi, PID: 14933
E/AndroidRuntime(14933): java.lang.NullPointerException: Attempt to invoke interface method 'void org.thoughtcrime.securesms.components.ThumbnailView$ThumbnailClickListener.onClick(android.view.View, org.thoughtcrime.securesms.mms.Slide)' on a null object reference
E/AndroidRuntime(14933): 	at org.thoughtcrime.securesms.components.ThumbnailView$ThumbnailClickDispatcher.onClick(ThumbnailView.java:180)
E/AndroidRuntime(14933): 	at android.view.View.performClick(View.java:4780)
E/AndroidRuntime(14933): 	at android.view.View$PerformClick.run(View.java:19866)
E/AndroidRuntime(14933): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(14933): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(14933): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(14933): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(14933): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(14933): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(14933): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(14933): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
I/Process (14933): Sending signal. PID: 14933 SIG: 9
```

some errors in a future that may be related to crash, comes after crash
```
W/PartDatabase( 8094): inserting part to mms 3
W/PartDatabase( 8094): Writing part data from URI
W/MessageSender( 8094): ws.com.google.android.mms.MmsException: java.io.FileNotFoundException: java.io.FileNotFoundException: Failed to find document file.
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.writePartData(PartDatabase.java:401)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.insertPart(PartDatabase.java:438)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.insertParts(PartDatabase.java:228)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.MmsDatabase.insertMediaMessage(MmsDatabase.java:755)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.MmsDatabase.insertMessageOutbox(MmsDatabase.java:724)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.sms.MessageSender.send(MessageSender.java:102)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.ConversationActivity$14.doInBackground(ConversationActivity.java:1044)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.ConversationActivity$14.doInBackground(ConversationActivity.java:1041)
W/MessageSender( 8094): 	at android.os.AsyncTask$2.call(AsyncTask.java:292)
W/MessageSender( 8094): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/MessageSender( 8094): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
W/MessageSender( 8094): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/MessageSender( 8094): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/MessageSender( 8094): 	at java.lang.Thread.run(Thread.java:818)
W/MessageSender( 8094): Caused by: java.io.FileNotFoundException: java.io.FileNotFoundException: Failed to find document file.
W/MessageSender( 8094): 	at android.database.DatabaseUtils.readExceptionWithFileNotFoundExceptionFromParcel(DatabaseUtils.java:146)
W/MessageSender( 8094): 	at android.content.ContentProviderProxy.openTypedAssetFile(ContentProviderNative.java:691)
W/MessageSender( 8094): 	at android.content.ContentResolver.openTypedAssetFileDescriptor(ContentResolver.java:1080)
W/MessageSender( 8094): 	at android.content.ContentResolver.openAssetFileDescriptor(ContentResolver.java:921)
W/MessageSender( 8094): 	at android.content.ContentResolver.openInputStream(ContentResolver.java:646)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.mms.PartAuthority.getPartStream(PartAuthority.java:44)
W/MessageSender( 8094): 	at org.thoughtcrime.securesms.database.PartDatabase.writePartData(PartDatabase.java:395)
W/MessageSender( 8094): 	... 13 more
```

### LINKED ISSUE #3044: NPE: ThumbnailView, tap preview icon of media message draft
encountered this while running an unmodified debug build of 27a5b7dd5c588abd677b6947c896df410d67a0f2, steps to reproduce:

1) open conversation
2) click add attachment
3) select any picture
4) tap on preview before sending
5) crash

crash log >> https://gist.github.com/rhodey/b791b99d3efb34d423b4

NPE occurs on same line as #3042
```
04-23 10:42:50.356    2532-2532/org.thoughtcrime.securesms.sushi D/AndroidRuntime﹕ Shutting down VM
04-23 10:42:50.372    2532-2532/org.thoughtcrime.securesms.sushi E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: org.thoughtcrime.securesms.sushi, PID: 2532
    java.lang.NullPointerException: Attempt to invoke interface method 'void org.thoughtcrime.securesms.components.ThumbnailView$ThumbnailClickListener.onClick(android.view.View, org.thoughtcrime.securesms.mms.Slide)' on a null object reference
            at org.thoughtcrime.securesms.components.ThumbnailView$ThumbnailClickDispatcher.onClick(ThumbnailView.java:180)
            at android.view.View.performClick(View.java:4780)
            at android.view.View$PerformClick.run(View.java:19866)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

### PR DESCRIPTION
**Pull request by mcginty**
Fixes #3042
Fixes #3044
// FREEBIE

### CODE REVIEW

**Comment by rhodey** [comment]
I agree that this should prevent NPE in both cases, and the resulting UX is probably fine for #3044, but with #3042 the user is just left with an error image or in some cases an empty white space.

I can open another issue for that I spose.

**Comment by mcginty** [comment]
@rhodey i tried reproducing with photos synced on my google drive and never got the error images. can you send me an example image that was causing this? wondering if it's the image that's causing a skia bug or something.

**Comment by rhodey** [comment]
@mcginty I just checked out 28232fc2a5f8ac8ba11283ca9992f1052467d28b in an attempt to test if this was new behavior related to glide, while testing that I was unable to reproduce this bug, then I switched back to master @ 424a463b21869b9afa674430709a4dc3e03be31c and was also unable to reproduce this bug.

I mentioned in the issue report that strangely after attempting to attach the image 2-3 times it would load correctly (ie no FileNotFoundException). My thoughts at this time are that:

1) prior to this pull we handled all FileNotFoundExceptions bad, not just google drive
2) the actual cause of the FNFE was actually the fault of google drive

I'm going to spend a few more minutes trying to reproduce this but no longer too concerned that the FNFE will surface for many users. what do ya think?

**Comment by 2-4601** [comment]
> 1) prior to this pull we handled all FileNotFoundExceptions bad

Will this also solve this case:
1. Remove a picture that's in your device with a file manager
2. Attach that picture to a TS message (the gallery viewer does not know the picture was deleted)
3. TS will create an "empty" message that gets stuck in a pending state forever

However TS does not crash.

I was just going to file this bug report with a demonstration but then I found this discussion.

If you try to do the same in Google Hangouts you will get a 'Can't find picture' error notification.

**Comment by rhodey** [comment]
@2-4601 we're trying to do a release today so this pull mostly exists to prevent the crash, I agree that there is still definitely an issue with how this situation is handled. It's probably best to open a new issue with the steps to reproduce that you described. Thanks for taking the time to identify reliable steps to reproduce :D

**Pull request closed without merging**
