### PR TITLE
always save drafts

### LINKED ISSUE #1897: message drafts sometimes lost
Hi,
I experienced some frustration when starting a few messages, I had to check and copy some details to complete my messages.
Coming back to my uncompleted messages, each time, no draft was memorized so I had to start all over ...
Hope I am clear.
Did I miss something or do others share the same issue ?
Thank you.

Pierre Marie
Paris, France

### PR DESCRIPTION
**Pull request by rhodey**
1) moved 'saveDraft()' call from 'onDestroy()' to 'onPause()'
2) dropped 'saveDraft()' call from 'onNewIntent()' because Android guarantees 'onPause()' will always be called before 'onNewIntent()'

Fixes #1897
// FREEBIE

### CODE REVIEW

**Comment by moxie0** [comment]
iirc this is the way it is for a reason

**Comment by rhodey** [comment]
@moxie0 as far as I can tell `saveDraft()` has only ever moved about in these following commits:

1) first commit with support for resuming drafts https://github.com/WhisperSystems/TextSecure/commit/bf92de394b2ce576d04700f2267edb7b46dbc30c#diff-8b6badc7254f2d75634d87a85bc9cd31R179

2) moved from `onDestroy()` to `onStop()` https://github.com/WhisperSystems/TextSecure/commit/990902845af5a21e241db14204b783565c381501#diff-8b6badc7254f2d75634d87a85bc9cd31

3) moved back to `onDestroy()` when use of the `onNewIntent()` method began https://github.com/WhisperSystems/TextSecure/commit/1443d846c4b151b4e8d7440a1560aa688c19e6e4#diff-8b6badc7254f2d75634d87a85bc9cd31R233

Android doc does not guarantee that either [onStop()](http://developer.android.com/reference/android/app/Activity.html#onStop()) or [onDestory()](http://developer.android.com/reference/android/app/Activity.html#onDestroy()) will ever be called and the doc for `onDestory()` specifically recommends that we instead save our drafts using `onPause()`. 

Tested with text and image and text + image drafts in a variety of cases.

**Comment by McLoo** [comment]
@rhodey did you try changing attachments like described in #2232

**Comment by rhodey** [comment]
@McLoo 

I don't know if I'm understanding the exact issue addressed by #2232, are you saying the failure mode was caused by something like:

1) type something in the message EditText
2) add an image from the attachment manager
3) replace that draft image with another from the attachment manager

**Comment by rhodey** [comment]
## test cases

### text draft, pause, resume
1) write text
2) open recent activity view
3) reopen TextSecure
4) text draft is restored

### text draft, back, conversation select
1) write text
2) go back to the conversation list view
3) reopen the conversation
4) text draft is restored

### text draft, destroy, conversation select
1) write text
2) open recent activity view
3) force close TextSecure
4) reopen TextSecure
5) reopen the conversation
6) text draft is restored

### text + image draft, pause, resume
1) write text
2) add attachment
3) open recent activity view
4) reopen TextSecure
5) text + image draft is restored

### text + image draft, back, conversation select
1) write text
2) add attachment
3) go back to the conversation list view
4) reopen the conversation
5) text + image draft is restored

### text + image draft, destroy, conversation select
1) write text
2) add attachment
3) open recent activity view
4) force close TextSecure
5) reopen TextSecure
6) reopen the conversation
7) text + image draft is restored

### attach image, remove image, pause, resume
1) attach image
2) remove image
3) open recent activity view
4) reopen TextSecure
5) no image in draft

### attach image, pause, resume, attach new image, pause, resume
1) attach image
2) open recent activity view
3) reopen TextSecure
4) image is in draft
5) attach new image
6) open recent activity view
7) reopen TextSecure
8) new image is in draft

@McLoo anything else you recommend testing?

**Comment by McLoo** [comment]
@rhodey the one before the last gets close. 
1) attach image
2) go back to the conversation list view
3) reopen the conversation
4) text + image draft is restored
5) attach new image
6)... new or old image?

**Comment by rhodey** [comment]
@McLoo 

6)... new image :)

thanks for the test cases!

**Comment by rhodey** [comment]
rebased with master 62181a3d7f59a4b1e2738411291abfbd30d1d794 and ran through the above tests again, still behaving as expected.

**Pull request closed without merging**
