### PR TITLE
Support for direct photo capture from app.

### PR DESCRIPTION
**Pull request by moxie0**
Make the send button toggle to an attach button when the
compose text and attachments are emmpty.

Part of #520

// FREEBIE

### CODE REVIEW

**Comment by rhodey** [comment]
the diff looks good to me, I'd rename `cleanup()` to be more descriptive given that we already have a `clear()` but w/e.

switching between the attachment icon and the send button on my N5 causes the layout containing the emoji toggle, edit text, and animating toggle to change in size by a few pixels. also from an empty edit text with the attachment icon present, if I type a letter and then immediately tap the attach icon I can break the toggle state to show a send icon when the edit text is empty.

**Comment by rhodey** [comment]
the change in layout size that I mentioned above also happens in #3198, tagging as possibly related.

**Comment by McLoo** [comment]
shouldn't `<uses-permission android:name="android.permission.CAMERA" />` be added to the manifest.xml?

*really don't know whether I should comment on a pulled PR or the commit - ignoring the question if the comment is helpful anyway:D*

**Comment by moxie0** [comment]
@McLoo As an intermediate step we're using an intent to open the camera app and take the picture for us, so we don't actually need permission to access the camera directly.  @turtlekiosk is working on a PR to do direct camera access for a better experience, and we'll need that permission then.

**Comment by moxie0** [comment]
(and yeah i think commenting on the pr is better than the commit)

**Pull request closed without merging**
