### PR TITLE
Updated Transport UI to be more "Hangouts-Like"

### PR DESCRIPTION
**Pull request by samlanning**
Following comments on #2285 #845 #1724.

UI is now suitable to allow for persistent transport selection. 

**Screenshots:**

SMS Only Contact

Other Contacts

### CODE REVIEW

**Comment by samlanning** [comment]
@mcginty: I believe this is your domain?

**Comment by samlanning** [comment]
I'm thinking perhaps I need to add a bit of green through the loop of the lock on the SMS icons?

**Comment by agrajaghh** [comment]
Isn't `Secure SMS` missing in the last screenshot?

**Comment by samlanning** [comment]
@agrajaghh it's like that for me with current master too, I haven't changed the behaviour as to what transports are enabled.

**Comment by samlanning** [comment]
I have got contacts where all three are enabled however...

**Comment by agrajaghh** [comment]
okay :)

**Comment by samlanning** [comment]
Rebased ontop of current head, and replaced TS transport icon with latest logo.

@mcginty

**Comment by moxie0** [comment]
Thanks, but we're thinking of adding a tool tip for our current send button selector instead of breaking things out into a separate component.

**Pull request closed without merging**
