### PR TITLE
migrate GroupMembersDialog to material-dialogs

### PR DESCRIPTION
**Pull request by agrajaghh**
better alternative to #2490 

**Android 5, light theme:**
light

**Android 5, dark theme:**
dark

**Android 2.3, light theme:**
2 3 light

**Android 2.3, dark theme:**
2 3 dark

The title seems too long, what do you think about "Group members"?

### CODE REVIEW

**Comment by mcginty** [comment]
Was just about to suggest "Group members" as the string, before I read the last sentence. Yes, I think that's much better.

**Comment by mcginty** [comment]
Only other thought is we can also use the material icon instead of my thrown-together Holo version. (it's `ic_group` prefix in the icon repo)

ic_group_grey600_24dp

**Comment by agrajaghh** [comment]
done and done:

light
dark

I used the grey icon not the black one for the light theme, thats correct, right?

**Comment by agrajaghh** [comment]
I just saw that the [Material Icons](https://github.com/google/material-design-icons#license) are under the Attribution license. That means we have to give credit and a link to the license somewhere, no?

**Comment by mcginty** [comment]
Yeah, that sounds right. I'm guessing this is something we can just throw in a markdown file in the repo? @moxie0 any idea?

**Comment by agrajaghh** [comment]
Doesn't it have to be included in the derivative work/app itself?

**Comment by agrajaghh** [comment]
rebased

**Comment by agrajaghh** [comment]
closing in favor of #2743

**Pull request closed without merging**
